-- Doctrine Migration File Generated on 2019-08-07 10:52:19

-- Version 20190807084647
CREATE TABLE vehicle_checkout (id INT AUTO_INCREMENT NOT NULL, vehicle_id INT NOT NULL, date_of_checkout DATE NOT NULL, description LONGTEXT DEFAULT NULL, type SMALLINT NOT NULL, mileage INT NOT NULL, components_changed JSON DEFAULT NULL COMMENT '(DC2Type:json_array)', total_cost DOUBLE PRECISION DEFAULT NULL, INDEX IDX_722A22DA545317D1 (vehicle_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
CREATE TABLE vehicle_assignement (id INT AUTO_INCREMENT NOT NULL, vehicle_id INT NOT NULL, driver_id INT NOT NULL, date_ofassigning DATE NOT NULL, date_of_revoking DATE DEFAULT NULL, observation VARCHAR(255) DEFAULT NULL, INDEX IDX_6969CE1C545317D1 (vehicle_id), INDEX IDX_6969CE1CC3423909 (driver_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
CREATE TABLE driver (id INT AUTO_INCREMENT NOT NULL, first_name VARCHAR(60) NOT NULL, last_name VARCHAR(60) NOT NULL, license_number VARCHAR(255) NOT NULL, birthday DATE DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
CREATE TABLE vehicle (id INT AUTO_INCREMENT NOT NULL, make VARCHAR(255) NOT NULL, model VARCHAR(255) NOT NULL, date_of_circulation DATE NOT NULL, date_of_acquisition DATE NOT NULL, immatriculation_number VARCHAR(255) NOT NULL, grey_card_number VARCHAR(255) NOT NULL, type VARCHAR(255) DEFAULT NULL, availability TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
CREATE TABLE sinister (id INT AUTO_INCREMENT NOT NULL, vehicle_id INT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, date_of_sinister DATE NOT NULL, damage_estimation DOUBLE PRECISION DEFAULT NULL, INDEX IDX_73FC7B36545317D1 (vehicle_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
ALTER TABLE vehicle_checkout ADD CONSTRAINT FK_722A22DA545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id);
ALTER TABLE vehicle_assignement ADD CONSTRAINT FK_6969CE1C545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id);
ALTER TABLE vehicle_assignement ADD CONSTRAINT FK_6969CE1CC3423909 FOREIGN KEY (driver_id) REFERENCES driver (id);
ALTER TABLE sinister ADD CONSTRAINT FK_73FC7B36545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id);
INSERT INTO migration_versions (version, executed_at) VALUES ('20190807084647', CURRENT_TIMESTAMP);
